Repository HowMuchPay/HowMuchPay_BE, pull requests merged in 2023-08, with the labels that each got.

#37 [FEATURE-37] 캘린더 일정 조회 API
  src/main/java/com/example/howmuch/controller/CalendarController.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/domain/repository/MyEventRepository.java
  src/main/java/com/example/howmuch/dto/calendar/GetAcEventsCalendarResponseDto.java
  src/main/java/com/example/howmuch/dto/calendar/GetCalendarResponseDto.java
  src/main/java/com/example/howmuch/dto/calendar/GetMyEventsCalendarResponseDto.java
  src/main/java/com/example/howmuch/service/calendar/CalendarService.java
Labels: enhancement

#39 [FEATURE-39] 캘린더(통계) 조회 API
  src/main/java/com/example/howmuch/controller/CalendarController.java
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/domain/repository/MyEventRepository.java
  src/main/java/com/example/howmuch/dto/calendar/schedule/GetAcEventsCalendarResponseDto.java
  src/main/java/com/example/howmuch/dto/calendar/schedule/GetCalendarResponseDto.java
  src/main/java/com/example/howmuch/dto/calendar/schedule/GetMyEventsCalendarResponseDto.java
  src/main/java/com/example/howmuch/dto/calendar/statistics/GetStatisticsResponseDto.java
  src/main/java/com/example/howmuch/dto/calendar/statistics/StatisticsListResponse.java
  src/main/java/com/example/howmuch/dto/user/UserOauthLoginResponseDto.java
  src/main/java/com/example/howmuch/service/calendar/CalendarService.java
  src/main/java/com/example/howmuch/service/user/AuthService.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
Labels: enhancement

#40 [REFACTOR-40] 캘린더 통계 API 코드 리팩토링
  src/main/java/com/example/howmuch/dto/calendar/statistics/StatisticsListResponse.java
  src/main/java/com/example/howmuch/service/calendar/CalendarService.java
Labels: 👨‍🔧 refactor

#41 [REFACTOR-41] Access token 재발급 API 리팩토링
  src/main/java/com/example/howmuch/controller/UserController.java
  src/main/java/com/example/howmuch/service/user/AuthService.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
  src/main/java/com/example/howmuch/service/user/UserService.java
Labels: 👨‍🔧 refactor

#42 [FEATURE-42] 지인 경조사 단일 조회 (디데이) 및 내역 삭제 API
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/dto/event/GetAcEventsResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍💻 FEAT

#43 [FEATURE-43] 경조사비 추천 API 리팩토링
  src/main/java/com/example/howmuch/controller/RecommendationEventController.java
  src/main/java/com/example/howmuch/domain/repository/RecommendationEventRepository.java
  src/main/java/com/example/howmuch/dto/recommednation/CreateRecommendationEventRequestDto.java
  src/main/java/com/example/howmuch/service/recommendation/RecommendationEventService.java
Labels: 👨‍🔧 refactor

#44 [REFACTOR-44] 나의 경조사 등록 API EventTime 추가 리팩토링
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventRequestDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍🔧 refactor

#45 [REFACTOR-45] 나의 경조사 세부사항 조회 리팩토링 및 추가 구현
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/entity/MyEventDetail.java
  src/main/java/com/example/howmuch/domain/repository/MyEventDetailRepository.java
  src/main/java/com/example/howmuch/dto/event/GetAllMyEventDetailResponseDto.java
  src/main/java/com/example/howmuch/dto/event/GetMyEventInfoResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
  src/test/java/com/example/howmuch/test/GlobalTest.java
Labels: 👨‍🔧 refactor

#46 [Feature46] 경조사비 추천 알고리즘 등록(saveAll) API 추가
  src/main/java/com/example/howmuch/controller/RecommendationEventController.java
  src/main/java/com/example/howmuch/domain/entity/RecommendationEvent.java
  src/main/java/com/example/howmuch/dto/recommednation/CreateAverageAmountRequestDto.java
  src/main/java/com/example/howmuch/dto/recommednation/RelationInfo.java
  src/main/java/com/example/howmuch/service/recommendation/RecommendationEventService.java
Labels: enhancement, 👨‍💻 FEAT

#47 [Feature47] 경조사비 설문조사 페이지 추천값 조회 API
  src/main/java/com/example/howmuch/controller/RecommendationEventController.java
  src/main/java/com/example/howmuch/domain/entity/RecommendationEvent.java
  src/main/java/com/example/howmuch/domain/repository/RecommendationEventRepository.java
  src/main/java/com/example/howmuch/dto/recommednation/GetAverageAmountRequestDto.java
  src/main/java/com/example/howmuch/service/recommendation/RecommendationEventService.java
Labels: enhancement, 👨‍💻 FEAT

#48 [Refactor -48] 경조사비 추천 값 저장 및 조회 리팩토링
  src/main/java/com/example/howmuch/config/security/SecurityConfig.java
  src/main/java/com/example/howmuch/controller/RecommendationEventController.java
  src/main/java/com/example/howmuch/domain/repository/RecommendationEventRepository.java
  src/main/java/com/example/howmuch/dto/recommednation/CreateAverageAmountRequestDto.java
  src/main/java/com/example/howmuch/service/recommendation/RecommendationEventService.java
Labels: 👨‍🔧 refactor

#49 [FEATURE-49] 배포를 위한 설정 값 수정
  Dockerfile
  build.gradle
  src/main/java/com/example/howmuch/controller/RecommendationEventController.java
  src/main/java/com/example/howmuch/util/JwtService.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: enhancement

#50 [REFACTOR -50] getRecommendationApp API 리팩토링
  src/main/java/com/example/howmuch/controller/RecommendationEventController.java
  src/main/java/com/example/howmuch/domain/repository/RecommendationEventRepository.java
  src/main/java/com/example/howmuch/dto/recommednation/GetAppAverageAmountRequestDto.java
  src/main/java/com/example/howmuch/service/recommendation/RecommendationEventService.java
Labels: 👨‍🔧 refactor

#51 [REFACTOR-51] : 지인 경조사 등록 (내가 지불한 총 금액 추가)
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍🔧 refactor

#52 [Feature52] 지인 경조사 단일(디데이) 조회 API 추가
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/dto/event/GetAcEventsResponseDto.java
Labels: enhancement, 👨‍💻 FEAT

#53 [Refactor- 53] fcm 알림 API 리턴 값 수정 및 코드 리팩토링
  src/main/java/com/example/howmuch/controller/FcmNotificationController.java
  src/main/java/com/example/howmuch/dto/fcm/FcmNotificationRequestDto.java
  src/main/java/com/example/howmuch/dto/fcm/FcmNotificationRequestListDto.java
  src/main/java/com/example/howmuch/dto/fcm/FcmNotificationResponseDto.java
  src/main/java/com/example/howmuch/service/fcm/FcmNotificationService.java
Labels: enhancement, 👨‍🔧 refactor

#54 [Feature54 - HomeController API 구현
  src/main/java/com/example/howmuch/controller/HomeController.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/dto/Home/HomeResponseDto.java
  src/main/java/com/example/howmuch/service/user/UserService.java
Labels: enhancement, 👨‍💻 FEAT

#55 [REFACTOR-55] Cors 오류 수정
  src/main/java/com/example/howmuch/config/security/CorsConfig.java
  src/main/java/com/example/howmuch/controller/RecommendationEventController.java
  src/main/java/com/example/howmuch/dto/user/UserOauthLoginResponseDto.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
Labels: 👨‍🔧 refactor

#56 [Refactor56] 지인 경조사 필터링 조회 API 리팩토링
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: bug, 👨‍🔧 refactor

#57 [REFACTOR 57] getRecommendation 컨트롤러 (요청 타입 변경 ReqeustBody -> RequestParam
  src/main/java/com/example/howmuch/controller/RecommendationEventController.java
  src/main/java/com/example/howmuch/dto/recommednation/GetAppAverageAmountRequestDto.java
  src/main/java/com/example/howmuch/service/recommendation/RecommendationEventService.java
Labels: enhancement, 👨‍🔧 refactor
