Repository HowMuchPay/HowMuchPay_BE, pull requests merged in 2023-09, with the labels that each got.

#58 [REFACTOR-58] kakao oauth 방식 리팩토링
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationFilter.java
  src/main/java/com/example/howmuch/config/security/SecurityConfig.java
  src/main/java/com/example/howmuch/controller/HomeController.java
  src/main/java/com/example/howmuch/controller/KakaoOauthController.java
  src/main/java/com/example/howmuch/controller/UserController.java
  src/main/java/com/example/howmuch/dto/home/HomeResponseDto.java
  src/main/java/com/example/howmuch/dto/user/OauthTokenResponseDto.java
  src/main/java/com/example/howmuch/dto/user/login/UserInfoLoginRequestDto.java
  src/main/java/com/example/howmuch/dto/user/login/UserOauthLoginResponseDto.java
  src/main/java/com/example/howmuch/service/user/AuthService.java
  src/main/java/com/example/howmuch/service/user/KakaoOauthService.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
  src/main/java/com/example/howmuch/service/user/UserService.java
Labels: enhancement

#60 [REFACTOR-61] home 화면 조회 리팩토링 시 findColosetEvent가 없는 경우 반환 처리
  src/main/java/com/example/howmuch/service/user/UserService.java
Labels: bug, 👨‍🔧 refactor

#61 [Feature-61] s3 UploadFile 서비스 구현
  build.gradle
  src/main/java/com/example/howmuch/config/app/S3Config.java
  src/main/java/com/example/howmuch/controller/KakaoOauthController.java
  src/main/java/com/example/howmuch/service/s3/S3Service.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
Labels: enhancement, 👨‍💻 FEAT

#62 [REFACTOR -63] : 나의 경조사 내역 조회 기존 응답 구조 리팩토링
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/repository/MyEventRepository.java
  src/main/java/com/example/howmuch/dto/event/GetAllMyEventsResponse.java
  src/main/java/com/example/howmuch/dto/event/GetAllMyEventsResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: enhancement, 👨‍🔧 refactor

#63 [REFACTOR-64] 나의 경조사 내역 필터링 조회 리팩토링
  src/main/java/com/example/howmuch/controller/CalendarController.java
  src/main/java/com/example/howmuch/domain/repository/MyEventRepository.java
  src/main/java/com/example/howmuch/dto/calendar/schedule/GetCalendarResponseDto.java
  src/main/java/com/example/howmuch/dto/event/GetAllMyEventsResponseDto.java
  src/main/java/com/example/howmuch/service/calendar/CalendarService.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍💻 FEAT, 👨‍🔧 refactor

#64 [REFACTOR-65] : 지인 경조사 전체 내역 조회 응답구조 변경에 따른 리팩토링
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/dto/event/GetAllAcEventsResponse.java
  src/main/java/com/example/howmuch/dto/event/GetAllAcEventsResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: enhancement, 👨‍🔧 refactor

#66 [FIX-67] 지인 경조사 전체 조회, 필터링 조회 정렬 관련 오류 수정
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/domain/repository/MyEventRepository.java
  src/main/java/com/example/howmuch/service/event/EventService.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 👨‍🔧 refactor

#67 [FIX-68] 나의 경조사 전체 조회, 필터링 조회 정렬 관련 오류 수정
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍🔧 refactor

#68 [REFACTOR-69] 나의 경조사 필터링 조회시, 필터링된 나의 경조사의 비용만 계산하도록 리팩토링
  src/main/java/com/example/howmuch/dto/event/GetAllAcEventsResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍🔧 refactor

#69 [REFACTOR-70] 지인의 경조사 필터링 조회시, 필터링된 지인의 경조사의 비용만 계산하도록 리팩토링
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍🔧 refactor

#70 [REFACTOR-71] 지인 경조사 엔티티 클래스 `event_time` 필드 추가
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/dto/event/CreateAcEventRequestDto.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventRequestDto.java
Labels: 👨‍🔧 refactor

#71 [REFACTOR-72] 지인 경조사 등록 및 조회 응답 DTO 리팩토링 및 추가 구현
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/dto/event/CreateAcEventRequestDto.java
  src/main/java/com/example/howmuch/dto/event/GetAllAcEventsResponse.java
  src/main/java/com/example/howmuch/dto/event/GetAllAcEventsResponseDto.java
  src/main/java/com/example/howmuch/dto/event/GetAllMyEventsResponse.java
  src/main/java/com/example/howmuch/exception/event/EventExceptionHandler.java
  src/main/java/com/example/howmuch/exception/event/NeedEventNameException.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍🔧 refactor

#72 [REFACTOR-73] : 지인 경조사 등록 API 리팩토링
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventRequestDto.java
  src/main/java/com/example/howmuch/exception/event/EventExceptionHandler.java
  src/main/java/com/example/howmuch/exception/event/NeedEventCharacterNameException.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍🔧 refactor

#73 [Feature75] - 지인 이름으로 경조사 조회 API 구현
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/dto/event/GetAcEventsResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: enhancement, 👨‍💻 FEAT

#75 [Feature75] - 지인 이름으로 경조사 조회 API 구현
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/dto/event/GetAcEventsResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: enhancement, 👨‍💻 FEAT

#77 [Refactor77] - 지인 이름으로 경조사 조회 API 리팩토링
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: enhancement, 👨‍🔧 refactor

#78 [feature-78] Home 화면 조회시 MyEvent 조회 포함 API
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/domain/repository/MyEventRepository.java
  src/main/java/com/example/howmuch/dto/home/HomeResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
  src/main/java/com/example/howmuch/service/user/UserService.java
Labels: enhancement, 👨‍💻 FEAT, 👨‍🔧 refactor

#79 [feature-79] 유저 이미지 파일 s3 유저 이미지 파일 커넥션
  src/main/java/com/example/howmuch/config/app/S3Config.java
  src/main/java/com/example/howmuch/service/s3/S3Service.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
Labels: enhancement, 👨‍💻 FEAT

#80 [REFACTOR-80] 나의 경조사 삭제시, 내가 받은 나의 경조사 총 금액 비용 변경하도록 리팩토링
  src/main/java/com/example/howmuch/constant/MyType.java
  src/main/java/com/example/howmuch/domain/entity/User.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍💻 FEAT, 👨‍🔧 refactor

#81 [REFACTOR-81] 나의 경조사 세부사항 삭제시, 나의 경조사 받은 금액 및 해당 유저 총 받은 금액 차감하도록 리팩토링
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/repository/MyEventDetailRepository.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍💻 FEAT, 👨‍🔧 refactor

#82 [Refactor-82] 지인 경조사 리팩토링
  src/main/java/com/example/howmuch/domain/entity/User.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/service/event/EventService.java
  src/main/java/com/example/howmuch/service/user/UserService.java
Labels: 👨‍💻 FEAT, 👨‍🔧 refactor

#83 [REFACTOR-83] 공지사항 전체 조회 응답 DTO 리팩토링 및 회원 로그인 부분 로직 오류 수정
  src/main/java/com/example/howmuch/domain/entity/Notice.java
  src/main/java/com/example/howmuch/dto/notice/GetAllNoticeResponseDto.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
Labels: 👨‍💻 FEAT, 👨‍🔧 refactor

#84 [Refactor-84] 회원가입시 이미지 파일 S3 저장
  src/main/java/com/example/howmuch/service/s3/S3Service.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
Labels: enhancement, 👨‍💻 FEAT

#85 [Feature85] 나의 모든 경조사 조회 statistics API 구현
  src/main/java/com/example/howmuch/controller/HomeController.java
  src/main/java/com/example/howmuch/domain/entity/MyEventDetail.java
  src/main/java/com/example/howmuch/domain/repository/MyEventDetailRepository.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventDetailRequestDto.java
  src/main/java/com/example/howmuch/dto/event/GetAllStatisticsMyEventDetailResponseDto.java
  src/main/java/com/example/howmuch/dto/home/GetAllStatisticsResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: enhancement, 👨‍💻 FEAT

#88 [FEATURE-88] 캘린더 일정 조회 응답 구조 변경 및 CI 구축
  .github/workflows/CI.yml
  src/main/java/com/example/howmuch/controller/CalendarController.java
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/domain/repository/MyEventRepository.java
  src/main/java/com/example/howmuch/dto/calendar/schedule/GetAcEventsCalendarResponseDto.java
  src/main/java/com/example/howmuch/dto/calendar/schedule/GetCalendarResponseDto.java
  src/main/java/com/example/howmuch/dto/calendar/schedule/GetCalendarScheduleResponseDto.java
  src/main/java/com/example/howmuch/dto/calendar/schedule/GetMyEventsCalendarResponseDto.java
  src/main/java/com/example/howmuch/service/calendar/CalendarService.java
  src/main/java/com/example/howmuch/service/user/AuthService.java
Labels: enhancement, 👨‍🔧 refactor

#90 [Feature89] 지인 이름 조회 API 구현
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/dto/event/GetAllAcNicknameResponse.java
  src/main/java/com/example/howmuch/dto/event/GetAllAcNicknameResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: enhancement, 👨‍💻 FEAT

#91 [Feature90] - 추천 API 전화번호 추가 (설문조사 이벤트)
  src/main/java/com/example/howmuch/domain/entity/RecommendationEvent.java
  src/main/java/com/example/howmuch/dto/recommednation/CreateAverageAmountRequestDto.java
  src/main/java/com/example/howmuch/service/recommendation/RecommendationEventService.java
Labels: enhancement, 👨‍💻 FEAT

#92 [FEATURE-91] build.gradle 'io.netty:netty-resolver-dns-native-macos:4.1.68.Final:osx-aarch_64' 의존성 추가
  build.gradle
  src/main/java/com/example/howmuch/dto/recommednation/CreateAverageAmountRequestDto.java
Labels: enhancement, 👨‍💻 FEAT

#93 [feature-92] : 지인 경조사 상세 조회 기능 추가
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/dto/event/GetAcEventsResponseDto.java
Labels: enhancement, 👨‍💻 FEAT, 👨‍🔧 refactor

#95 [Feature-93] 나의 경조사 조회 API 구현 및 통계화면 조회시 반환 타입 변경
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/dto/event/GetMyEventsResponseDto.java
  src/main/java/com/example/howmuch/dto/home/CombinedEventResponse.java
  src/main/java/com/example/howmuch/dto/home/GetAllStatisticsResponseDto.java
  src/main/java/com/example/howmuch/dto/home/HomeResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: enhancement, 👨‍💻 FEAT, 👨‍🔧 refactor
