Repository HowMuchPay/HowMuchPay_BE, pull requests merged in 2023-10, with the labels that each got.

#96 [FEATURE-94] User(회원), Auth(인증) 부분 전반적인 코드 리팩토링
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/controller/UserController.java
  src/main/java/com/example/howmuch/service/user/AuthService.java
  src/main/java/com/example/howmuch/service/user/UserService.java
Labels: enhancement, 👨‍🔧 refactor

#97 [FEATURE-95] 나의 경조사 비용 낸 모든 사람 조회 API & 해당 지인과 관련된 모든 나의 경조사 조회 APO
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/repository/MyEventDetailRepository.java
  src/main/java/com/example/howmuch/dto/user/login/UserOauthLoginResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
  src/main/java/com/example/howmuch/service/user/KakaoOauthService.java
Labels: enhancement

#98 [Feature-96] 경조사비 추천알고리즘 로직 변경 (기획자)
  src/main/java/com/example/howmuch/domain/repository/RecommendationEventRepository.java
  src/main/java/com/example/howmuch/service/recommendation/RecommendationEventService.java
Labels: enhancement, 👨‍💻 FEAT, 👨‍🔧 refactor

#99 [FEATURE-97] 기존 CI.yml 수정
  .github/workflows/CI.yml
Labels: 👨‍🔧 refactor

#101 [Feature-99] API Url 변경 및 지인의 경조사 세부 사항 조회시 eventTime 추가
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/dto/event/CreateAcEventRequestDto.java
  src/main/java/com/example/howmuch/dto/event/GetAcEventsResponseDto.java
Labels: enhancement, 👨‍💻 FEAT, 👨‍🔧 refactor

#102 [REFACTOR-100]: 캘린더 일정 및 통계 관련 오류 수정 및 리팩토링 진행
  src/main/java/com/example/howmuch/controller/CalendarController.java
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/domain/repository/MyEventRepository.java
  src/main/java/com/example/howmuch/dto/calendar/statistics/GetStatisticsResponseDto.java
  src/main/java/com/example/howmuch/dto/calendar/statistics/StatisticsListResponse.java
  src/main/java/com/example/howmuch/service/calendar/CalendarService.java
Labels: 👨‍💻 FEAT, 👨‍🔧 refactor

#103 [Feature-101] 홈 화면 통계 조회 API 정렬 추가 및 지인 이름 리스트 반환 타입 변경
  src/main/java/com/example/howmuch/controller/HomeController.java
  src/main/java/com/example/howmuch/dto/event/GetAllAcNicknameResponseDto.java
  src/main/java/com/example/howmuch/dto/home/GetAllStatisticsResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: enhancement, 👨‍💻 FEAT, 👨‍🔧 refactor

#105 [FEATURE-103] : 캘린더 통계 조회 API 응답 로직 리팩토링
  src/main/java/com/example/howmuch/dto/calendar/statistics/GetStatisticsResponseDto.java
  src/main/java/com/example/howmuch/service/calendar/CalendarService.java
Labels: bug, 👨‍🔧 refactor

#107 [refactor-105] : fcm 토큰 메시지 전송 acId -> targetUserPhoneNumber
  src/main/java/com/example/howmuch/dto/fcm/FcmNotificationRequestDto.java
  src/main/java/com/example/howmuch/dto/fcm/FcmNotificationRequestListDto.java
  src/main/java/com/example/howmuch/service/fcm/FcmNotificationService.java
Labels: 👨‍🔧 refactor

#106 [FEATURE-104] 카카오 로그인 시, 응답 DTO 필드 변경
  src/main/java/com/example/howmuch/dto/user/login/UserOauthLoginResponseDto.java
  src/main/java/com/example/howmuch/service/user/KakaoOauthService.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
Labels: 👨‍🔧 refactor

#108 [feature -106] : 지인의 경조사 상세조회 getAcEventDisplayNameWithDetail 추가
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/dto/event/GetAcEventsResponseDto.java
Labels: enhancement, 👨‍💻 FEAT

#110 [FEATURE/108] GlobalExceptionHandler 구현 및 요청 객체 검증 필드 수정
  build.gradle
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationFilter.java
  src/main/java/com/example/howmuch/controller/AdminController.java
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/controller/KakaoOauthController.java
  src/main/java/com/example/howmuch/dto/event/CreateAcEventRequestDto.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventDetailRequestDto.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventRequestDto.java
  src/main/java/com/example/howmuch/dto/home/CombinedEventResponse.java
  src/main/java/com/example/howmuch/dto/home/GetAllStatisticsResponseDto.java
  src/main/java/com/example/howmuch/dto/notice/CreateNoticeRequestDto.java
  src/main/java/com/example/howmuch/dto/user/TokenFromOauthServer.java
  src/main/java/com/example/howmuch/dto/user/login/UserInfoLoginRequestDto.java
  src/main/java/com/example/howmuch/exception/ErrorMessage.java
  src/main/java/com/example/howmuch/exception/global/GlobalExceptionHandler.java
  src/main/java/com/example/howmuch/service/notice/NoticeService.java
  src/main/java/com/example/howmuch/service/user/AuthService.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
  src/main/java/com/example/howmuch/util/JwtService.java
Labels: 👨‍🔧 refactor
