Repository HowMuchPay/HowMuchPay_BE, pull requests merged in 2023-07, with the labels that each got.

#1 Feature1
  build.gradle
  pull_request_template.md
  src/main/java/com/example/howmuch/HowMuchPayApplication.java
  src/main/java/com/example/howmuch/config/UpperCaseNamingStrategy.java
  src/main/java/com/example/howmuch/config/security/CorsConfig.java
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationFilter.java
  src/main/java/com/example/howmuch/config/security/JwtProvider.java
  src/main/java/com/example/howmuch/config/security/SecurityConfig.java
  src/main/java/com/example/howmuch/config/web/WebConfig.java
  src/main/java/com/example/howmuch/domain/BaseTimeEntity.java
  src/main/java/com/example/howmuch/domain/entity/Member.java
  src/main/java/com/example/howmuch/dto/member/TokenInfo.java
  src/main/java/com/example/howmuch/exception/ErrorCode.java
  src/main/java/com/example/howmuch/exception/member/MemberService.java
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/example/howmuch/HowMuchPayApplicationTests.java
Labels: 👨‍💻 FEAT

#3 Feature3
  build.gradle
  pull_request_template_md
  src/main/java/com/example/howmuch/config/app/RedisConfig.java
  src/main/java/com/example/howmuch/config/app/RedisProperties.java
  src/main/java/com/example/howmuch/config/app/SwaggerConfig.java
  src/main/java/com/example/howmuch/config/app/UpperCaseNamingStrategy.java
  src/main/java/com/example/howmuch/config/app/WebConfig.java
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationFilter.java
  src/main/java/com/example/howmuch/config/security/SecurityConfig.java
  src/main/java/com/example/howmuch/contant/Token.java
  src/main/java/com/example/howmuch/controller/MemberController.java
  src/main/java/com/example/howmuch/domain/entity/User.java
  src/main/java/com/example/howmuch/domain/repository/UserRepository.java
  src/main/java/com/example/howmuch/dto/member/NeedDataUserOauthResponseDto.java
  src/main/java/com/example/howmuch/dto/member/NewAccessTokenResponseDto.java
  src/main/java/com/example/howmuch/dto/member/OauthTokenResponseDto.java
  src/main/java/com/example/howmuch/dto/member/UserOauthLoginResponseDto.java
  src/main/java/com/example/howmuch/dto/member/userInfo/KakaoOauthUserInfo.java
  src/main/java/com/example/howmuch/dto/member/userInfo/OauthUserInfo.java
  src/main/java/com/example/howmuch/exception/ErrorCode.java
  src/main/java/com/example/howmuch/exception/member/InvalidTokenException.java
  src/main/java/com/example/howmuch/exception/member/UnauthorizedMemberException.java
  src/main/java/com/example/howmuch/service/member/AuthService.java
  src/main/java/com/example/howmuch/service/member/MemberService.java
  src/main/java/com/example/howmuch/service/member/OauthService.java
  src/main/java/com/example/howmuch/util/AuthTransformUtil.java
  src/main/java/com/example/howmuch/util/JwtService.java
  src/main/java/com/example/howmuch/util/RedisUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-redis.yml
  src/main/resources/application.yml
Labels: enhancement

#5 FEAT : Kakao Oauth 소셜 로그인 구현 완료
  build.gradle
  src/main/java/com/example/howmuch/config/app/AppConfig.java
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationFilter.java
  src/main/java/com/example/howmuch/config/security/SecurityConfig.java
  src/main/java/com/example/howmuch/dto/user/OauthTokenResponseDto.java
  src/main/java/com/example/howmuch/util/RedisUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-redis.yml
Labels: duplicate, enhancement

#7 [FEATURE-6] fcm 리팩토링 및 테스트
  build.gradle
  src/main/java/com/example/howmuch/config/fcm/FcmConfig.java
  src/main/java/com/example/howmuch/controller/FcmNotificationController.java
  src/main/java/com/example/howmuch/controller/FirebaseTokenController.java
  src/main/java/com/example/howmuch/domain/entity/FirebaseToken.java
  src/main/java/com/example/howmuch/domain/entity/User.java
  src/main/java/com/example/howmuch/domain/repository/FirebaseTokenRepository.java
  src/main/java/com/example/howmuch/domain/repository/UserRepository.java
  src/main/java/com/example/howmuch/dto/fcm/FcmNotificationRequestDto.java
  src/main/java/com/example/howmuch/exception/user/UserExceptionHandler.java
  src/main/java/com/example/howmuch/service/fcm/FcmNotificationService.java
  src/main/java/com/example/howmuch/service/fcm/FireBaseTokenService.java
  src/main/java/com/example/howmuch/util/SecurityUtil.java
  src/main/resources/application-dev.yml
Labels: enhancement

#8 [FEATURE-7] 나의 경조사 등록 API
  src/main/java/com/example/howmuch/contant/AcType.java
  src/main/java/com/example/howmuch/contant/EventCategory.java
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/domain/repository/MyEventRepository.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventRequestDto.java
  src/main/java/com/example/howmuch/exception/event/EventExceptionHandler.java
  src/main/java/com/example/howmuch/service/event/EventService.java
  src/main/resources/application-dev.yml
Labels: enhancement

#9 [FEATURE-8] 나의 모든 경조사 조회 API
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/repository/MyEventRepository.java
  src/main/java/com/example/howmuch/dto/event/GetAllMyEventsResponse.java
  src/main/java/com/example/howmuch/dto/event/GetAllMyEventsResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: enhancement

#10 [FEATURE-9] 지인 경조사 등록 API
  src/main/java/com/example/howmuch/contant/AcType.java
  src/main/java/com/example/howmuch/contant/EventCategory.java
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/entity/User.java
  src/main/java/com/example/howmuch/dto/event/CreateAcEventRequestDto.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventRequestDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: enhancement

#11 [FEATURE-10] 지인 경조사 조회 API
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationFilter.java
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/dto/event/GetAllAcEventsResponse.java
  src/main/java/com/example/howmuch/dto/event/GetAllAcEventsResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
  src/main/resources/application-dev.yml
Labels: enhancement

#12 [FEATURE-11] 지인 경조사 필터링 조회 API
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/dto/event/CreateAcEventRequestDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
  src/main/resources/application-dev.yml
Labels: duplicate, enhancement

#13 [FEATURE-12] jwt access token 재발급 API
  src/main/java/com/example/howmuch/config/security/SecurityConfig.java
  src/main/java/com/example/howmuch/controller/UserController.java
  src/main/java/com/example/howmuch/service/user/AuthService.java
Labels: enhancement

#14 FEAT : 회원 로그아웃 API 구현
  src/main/java/com/example/howmuch/controller/UserController.java
  src/main/java/com/example/howmuch/service/user/AuthService.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
Labels: enhancement

#15 [FEATURE-14] 나의 경조사 세부사항 등록 API
  src/main/java/com/example/howmuch/contant/AcType.java
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/entity/MyEventDetail.java
  src/main/java/com/example/howmuch/domain/entity/User.java
  src/main/java/com/example/howmuch/domain/repository/MyEventDetailRepository.java
  src/main/java/com/example/howmuch/dto/event/CreateAcEventRequestDto.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventDetailRequestDto.java
  src/main/java/com/example/howmuch/exception/event/EventExceptionHandler.java
  src/main/java/com/example/howmuch/exception/event/NotFoundEventException.java
  src/main/java/com/example/howmuch/service/event/EventService.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
Labels: enhancement

#16 [FEATURE-15] 나의 경조사 세부사항 조회 API
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/entity/MyEventDetail.java
  src/main/java/com/example/howmuch/domain/entity/User.java
  src/main/java/com/example/howmuch/domain/repository/MyEventDetailRepository.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventDetailRequestDto.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventRequestDto.java
  src/main/java/com/example/howmuch/dto/event/GetAllMyEventDetailResponseDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
Labels: enhancement

#17 [FEATURE-16] 나의 경조사 세부사항 이름 조회 API
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/repository/MyEventDetailRepository.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: enhancement

#19 [Feature18] - 추천 테이블 생성 및 저장 API
  src/main/java/com/example/howmuch/controller/RecommendationEventController.java
  src/main/java/com/example/howmuch/domain/entity/RecommendationEvent.java
  src/main/java/com/example/howmuch/domain/repository/RecommendationEventRepository.java
  src/main/java/com/example/howmuch/dto/recommednation/RecommendationEventRequestDto.java
  src/main/java/com/example/howmuch/service/recommendation/RecommendationEventService.java
Labels: enhancement, 👨‍💻 FEAT

#21 Feature20
  src/main/java/com/example/howmuch/contant/AcType.java
  src/main/java/com/example/howmuch/contant/EventCategory.java
  src/main/java/com/example/howmuch/dto/event/CreateAcEventRequestDto.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventDetailRequestDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍🔧 refactor

#22 [FEATURE - 21] 요구사항에 변경에 따른 전반적인 리팩토링 #02
  src/main/java/com/example/howmuch/contant/MyType.java
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventRequestDto.java
  src/main/resources/application-dev.yml
Labels: 👨‍🔧 refactor

#23 [FEATURE-22] 나의 경조사 필터링 조회 API
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/domain/repository/MyEventRepository.java
  src/main/java/com/example/howmuch/dto/event/CreateAcEventRequestDto.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventRequestDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
  src/main/resources/application-dev.yml
Labels: enhancement

#25 [FEATURE-25] 회원 탈퇴 API 구현
  src/main/java/com/example/howmuch/domain/BaseTimeEntity.java
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/entity/FirebaseToken.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/entity/MyEventDetail.java
  src/main/java/com/example/howmuch/domain/entity/RecommendationEvent.java
  src/main/java/com/example/howmuch/domain/entity/User.java
  src/main/resources/application-dev.yml
Labels: 👨‍💻 FEAT

#26 [FEATURE-26] 공지사항 등록 API
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationFilter.java
  src/main/java/com/example/howmuch/config/security/SecurityConfig.java
  src/main/java/com/example/howmuch/config/security/Token.java
  src/main/java/com/example/howmuch/config/security/UserAuthentication.java
  src/main/java/com/example/howmuch/constant/AcType.java
  src/main/java/com/example/howmuch/constant/EventCategory.java
  src/main/java/com/example/howmuch/constant/MyType.java
  src/main/java/com/example/howmuch/constant/RoleType.java
  src/main/java/com/example/howmuch/controller/AdminController.java
  src/main/java/com/example/howmuch/domain/entity/AcEvent.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/entity/Notice.java
  src/main/java/com/example/howmuch/domain/entity/RecommendationEvent.java
  src/main/java/com/example/howmuch/domain/entity/User.java
  src/main/java/com/example/howmuch/domain/repository/AcEventRepository.java
  src/main/java/com/example/howmuch/domain/repository/MyEventRepository.java
  src/main/java/com/example/howmuch/domain/repository/NoticeRepository.java
  src/main/java/com/example/howmuch/domain/repository/RecommendationEventRepository.java
  src/main/java/com/example/howmuch/dto/event/CreateAcEventRequestDto.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventRequestDto.java
  src/main/java/com/example/howmuch/dto/notice/createNoticeRequestDto.java
  src/main/java/com/example/howmuch/dto/recommednation/CalculateAverageAmountRequestDto.java
  src/main/java/com/example/howmuch/dto/recommednation/CreateRecommendationEventRequestDto.java
  src/main/java/com/example/howmuch/service/event/EventService.java
  src/main/java/com/example/howmuch/service/notice/NoticeService.java
  src/main/java/com/example/howmuch/service/recommendation/RecommendationEventService.java
  src/main/java/com/example/howmuch/service/user/AuthService.java
  src/main/java/com/example/howmuch/service/user/OauthService.java
  src/main/java/com/example/howmuch/util/JwtService.java
Labels: enhancement, 👨‍💻 FEAT

#27 [REFACTOR-26] 나의 경조사 등록 API 리팩토링
  src/main/java/com/example/howmuch/config/security/JwtAuthenticationFilter.java
  src/main/java/com/example/howmuch/config/security/SecurityConfig.java
  src/main/java/com/example/howmuch/constant/EventCategory.java
  src/main/java/com/example/howmuch/constant/MyType.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventRequestDto.java
  src/main/java/com/example/howmuch/service/user/AuthService.java
Labels: 👨‍🔧 refactor

#28 [FEATURE-28] 사용자(USER) 공지사항 조회 API
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/controller/NoticeController.java
  src/main/java/com/example/howmuch/domain/entity/Notice.java
  src/main/java/com/example/howmuch/dto/notice/GetAllNoticeResponseDto.java
  src/main/java/com/example/howmuch/service/notice/NoticeService.java
Labels: enhancement

#29 [FEATURE-29] 관리자(ADMIN) 공지사항 수정 API
  src/main/java/com/example/howmuch/controller/AdminController.java
  src/main/java/com/example/howmuch/domain/entity/Notice.java
  src/main/java/com/example/howmuch/dto/UpdateNoticeRequestDto.java
  src/main/java/com/example/howmuch/exception/notice/NotFoundNoticeException.java
  src/main/java/com/example/howmuch/exception/notice/NoticeExceptionHandler.java
  src/main/java/com/example/howmuch/service/notice/NoticeService.java
Labels: 👨‍💻 FEAT

#30 [FEATURE-30] 관리자(ADMIN) 공지사항 삭제 API
  src/main/java/com/example/howmuch/controller/AdminController.java
  src/main/java/com/example/howmuch/service/notice/NoticeService.java
Labels: 👨‍💻 FEAT

#31 [REFACTOR-31] 사용자(USER) 공지사항 조회 API 리팩토링
  src/main/java/com/example/howmuch/config/security/SecurityConfig.java
  src/main/java/com/example/howmuch/controller/AdminController.java
  src/main/java/com/example/howmuch/domain/BaseTimeEntity.java
  src/main/java/com/example/howmuch/domain/entity/Notice.java
  src/main/java/com/example/howmuch/dto/notice/GetAllNoticeResponseDto.java
Labels: 👨‍🔧 refactor

#32 [FEATURE-32] 회원 전화번호 추가 API
  src/main/java/com/example/howmuch/controller/UserController.java
  src/main/java/com/example/howmuch/domain/entity/User.java
  src/main/java/com/example/howmuch/service/user/UserService.java
  src/main/resources/application-dev.yml
Labels: enhancement, 👨‍💻 FEAT

#33 [Feature33] - FCM Service 로직 변경
  src/main/java/com/example/howmuch/controller/FcmNotificationController.java
  src/main/java/com/example/howmuch/domain/entity/User.java
  src/main/java/com/example/howmuch/domain/repository/UserRepository.java
  src/main/java/com/example/howmuch/dto/fcm/FcmNotificationRequestDto.java
  src/main/java/com/example/howmuch/dto/fcm/FcmNotificationRequestListDto.java
  src/main/java/com/example/howmuch/exception/user/PhoneNumberAlreadyExistsException.java
  src/main/java/com/example/howmuch/exception/user/UserExceptionHandler.java
  src/main/java/com/example/howmuch/service/fcm/FcmNotificationService.java
  src/main/java/com/example/howmuch/service/user/UserService.java
Labels: 👨‍💻 FEAT, 👨‍🔧 refactor

#34 [FEATURE-34] 나의 경조사 내역 삭제 API 및 SecurityConfig 리팩토링
  src/main/java/com/example/howmuch/config/security/SecurityConfig.java
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/service/event/EventService.java
Labels: 👨‍💻 FEAT, 👨‍🔧 refactor

#36 [REFACTOR-36] 엔티티 리팩토링 & 나의 경조사 조회 리팩토링
  src/main/java/com/example/howmuch/controller/EventController.java
  src/main/java/com/example/howmuch/domain/entity/MyEvent.java
  src/main/java/com/example/howmuch/domain/entity/User.java
  src/main/java/com/example/howmuch/dto/event/CreateMyEventRequestDto.java
  src/main/java/com/example/howmuch/dto/event/GetAllMyEventsResponse.java
Labels: 👨‍🔧 refactor
